# SPDX-License-Identifier: MIT
---
- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

# Examples of some tasks:
- name: Ensure required packages are installed
  ansible.builtin.package:
    name: "{{ __aide_packages }}"
    state: present
    use: "{{ (__aide_is_ostree | d(false)) |
             ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
  tags:
    - never
    - install

- name: Ensure required services are enabled and started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ __aide_services }}"
  tags:
    - never

- name: Generate "/etc/{{ __aide_config }}"
  ansible.builtin.template:
    src: "{{ __aide_config }}.j2"
    dest: "/etc/{{ __aide_config }}"
    backup: true
    mode: "0400"
  tags:
    - never
    - generate_config

- name: Initialize AIDE database and fetch it
  become: true
  tags:
    - never
    - init
  block:
    - name: Initialize AIDE database
      ansible.builtin.command:
        cmd: aide --init

    - name: Fetch AIDE database
      ansible.builtin.fetch:
        src: "{{ __aide_db_new_name }}"
        dest: "{{ aide_db_fetch_dir }}"

    - name: Remove remote AIDE database file
      ansible.builtin.file:
        path: "{{ __aide_db_new_name }}"
        state: absent

- name: Check AIDE integrity
  become: true
  tags:
    - never
    - check
  block:
    - name: Copy AIDE reference database to remote
      ansible.builtin.copy:
        src:
          "{{ aide_db_fetch_dir }}/{{ inventory_hostname }}/var/lib/aide/\
          aide.db.new.gz"
        dest: "{{ __aide_db_name }}"
        owner: root
        group: root
        mode: "0440"

    - name: Check against AIDE reference database
      ansible.builtin.command:
        cmd: aide --check
      changed_when: false

- name: Update AIDE database and fetch it
  become: true
  tags:
    - never
    - update
  block:
    - name: Update AIDE database
      ansible.builtin.command:
        cmd: aide --update
      register: __aide_update_result
      failed_when: __aide_update_result.rc > 7

    - name: Fetch AIDE database
      ansible.builtin.fetch:
        src: "{{ __aide_db_new_name }}"
        dest: "{{ aide_db_fetch_dir }}"

    - name: Remove remote AIDE database file
      ansible.builtin.file:
        path: "{{ __aide_db_new_name }}"
        state: absent
